// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuJqtlUpZqKvaC3RqgXSZ0sboDMhvIyt4',
    appId: '1:571138552806:web:630b14874bf8fd9aef5c27',
    messagingSenderId: '571138552806',
    projectId: 'blood-donation-app-b22eb',
    authDomain: 'blood-donation-app-b22eb.firebaseapp.com',
    storageBucket: 'blood-donation-app-b22eb.appspot.com',
    measurementId: 'G-NFT37ZPGEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0ixVttmuUqYxUEiOcIhuuuDARsSCMpGU',
    appId: '1:571138552806:android:db7d70d84796191bef5c27',
    messagingSenderId: '571138552806',
    projectId: 'blood-donation-app-b22eb',
    storageBucket: 'blood-donation-app-b22eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCESh3Tm1a343VEtLGTfyC5AwrdcpB5P9A',
    appId: '1:571138552806:ios:ec568415e7778c66ef5c27',
    messagingSenderId: '571138552806',
    projectId: 'blood-donation-app-b22eb',
    storageBucket: 'blood-donation-app-b22eb.appspot.com',
    iosBundleId: 'com.example.blood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCESh3Tm1a343VEtLGTfyC5AwrdcpB5P9A',
    appId: '1:571138552806:ios:ec568415e7778c66ef5c27',
    messagingSenderId: '571138552806',
    projectId: 'blood-donation-app-b22eb',
    storageBucket: 'blood-donation-app-b22eb.appspot.com',
    iosBundleId: 'com.example.blood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuJqtlUpZqKvaC3RqgXSZ0sboDMhvIyt4',
    appId: '1:571138552806:web:fda521040df3e461ef5c27',
    messagingSenderId: '571138552806',
    projectId: 'blood-donation-app-b22eb',
    authDomain: 'blood-donation-app-b22eb.firebaseapp.com',
    storageBucket: 'blood-donation-app-b22eb.appspot.com',
    measurementId: 'G-43S3S0P611',
  );
}
